#!/usr/bin/env bash

# Function to fetch record type and destination for a subdomain
domain=$1
get_dns_info() {
    local subdomain=$1
    local record_type
    local destination

    record_type=$(dig "$subdomain.$domain" | awk '/^;; ANSWER SECTION:/{getline; print $4}')
    destination=$(dig "$subdomain.$domain" | awk '/^;; ANSWER SECTION:/{getline; print $5}')

    echo "$record_type record and points to $destination"
}

# Validate the number of arguments
if [ "$#" -lt 1 ]; then
    echo "Domain name is mandatory"
    exit 1
fi

subdomain=$2

# Check if subdomain is not empty
if [ -n "$subdomain" ]; then
    result=$(get_dns_info "$subdomain")
    echo "The subdomain $subdomain is a $result"
else
    subdomains=("www" "lb-01" "web-01" "web-02")
    
    for subdomain in "${subdomains[@]}"; do
        result=$(get_dns_info "$subdomain")
        echo "The subdomain $subdomain is a $result"
    done
fi

