#!/usr/bin/env bash
# install nginx on the server

sudo apt-get -y update && sudo apt-get -y install nginx && sudo ufw allow 'Nginx HTTP'
if command -v nginx &> /dev/null; then
        sudo chmod -R 755 /var/www
	sudo mkdir -p /var/www/html

        # adjust the default html file to server another text
        cat <<EOF > /var/www/html/index.html
Hello World!
EOF
        # creating a symbolic link to the server block file
        nginx_conf="/etc/nginx/nginx.conf"
        sudo cp "$nginx_conf" "$nginx_conf.bak"
        # removing comment from a line in a file
        sudo sed -i 's/# server_names_hash_bucket_size 64;/server_names_hash_bucket_size 64;/g' "$nginx_conf"
        sudo systemctl reload nginx
fi
