#!/usr/bin/env bash

touch kunle
echo "$?"
if [ "$?" -eq 0 ]; then
	echo "$?"
	cat <<EOF >> kunle
<html>
    <head>
        <title>Welcome to Example.com!</title>
    </head>
    <body>
        <h1>Success! The example.com server block is working!</h1>
    </body>
</html>
EOF
	echo "i love you"
fi

