#!/bin/bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
#	The name of the custom HTTP header must be X-Served-By
#	The value of the custom HTTP header must be the hostname of the server Nginx is running on

if command -v nginx &> /dev/null; then
	redirect_url="https://www.chess.com/"
        cat <<EOF > /etc/nginx/sites-available/default
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

	add_header X-Served-By 441113-web-02;
        location /redirect_me {
                # First attempt to serve request as file, then
                # add a redirection to a particular url
                return 301 $redirect_url;
        }

        # add a custome error page
        error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /usr/share/nginx/html;
                internal;
        }
}
EOF
	# restart the nginx web server
	service nginx restart
fi
