#!/usr/bin/env bash
# Requirements:
# The MySQL dump must contain all your MySQL databases
# The MySQL dump must be named backup.sql
# The MySQL dump file has to be compressed to a tar.gz archive
# This archive must have the following name format: day-month-year.tar.gz
# The user to connect to the MySQL database must be root
# The Bash script accepts one argument that is the password used to connect to the MySQL database

day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
# the name of the archive file
archive_name="$day-$month-$year.tar.gz"

if [ -n "$1" ]; then
	echo "$1" | sudo mysqldump -u root --all-databases > backup.sql
else
	sudo mysqldump -u root --all-databases > backup.sql
fi
tar -czvf $archive_name backup.sql
