#!/usr/bin/env bash
#ping an IP address 5 times
if [ -z "$1" ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	count=0
	while [[ "$count" -lt 5 ]]; do
		ping "$1"
		count=$((count + 1));
	done
fi
