#!/usr/bin/env bash
# dubug nginx web server to listen to all traffic on port 80

# Use sed to replace the old listen directive with the new one
sed -i "s/listen [0-9]\+ default_server;/listen 80 default_server;/" /etc/nginx/sites-available/default

sudo service nginx restart
