#!/usr/bin/env bash
#This script is meant to print <Best School> 10 times with a while loop
#It also print some words at a particular iteration
count=0
while [[ "$count" -le 10 ]]; do
	if [[ "$count" -eq 3 ]]; then
		echo "bad luck"
	elif [[ "$count" -eq 7 ]]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count + 1)); 
done
