#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except the following TCP ports:
# 22 (SSH)
# 443 (HTTPS SSL)
# 80 (HTTP)

# Installed ufw if it is not already installed
sudo apt update && sudo apt install ufw

# Set default policies to deny incoming and allow outgoing traffic
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow SSH (port 22), HTTPS (port 443), and HTTP (port 80)
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable UFW and do not disrupt the existing ssh connection
sudo ufw enable
