#!/usr/bin/env bash
# fix a nginx webserver to run on an nginx user with less privillege

# stop the nginx server
service nginx stop

# add the nginx user if it doesn't exist
useradd -s /sbin/nologin -r -M nginx

# Update the Nginx configuration to run as the nginx user
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Update the default site configuration to listen on all active IPs on port 8080
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

# Start Nginx with the updated configuration
service nginx start
