#!/usr/bin/env bash
# fix a nginx webserver to run on an nginx user with less privillege

# stop the nginx server
service nginx stop

# add the nginx user if it doesn't exist
useradd -s /sbin/nologin -r -M nginx

# Update Nginx configuration to run as nginx user
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# change the config file to enable it to run on port 8080
cat <<EOF > /etc/nginx/sites-available/default
server {
        listen 8080 default_server;
        listen [::]:8080 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
}
EOF

# restart the nginx web server
service nginx restart
