#!/usr/bin/env bash
# fix a nginx webserver to run on an nginx user with less privillege
service nginx stop
useradd -s /sbin/nologin -r -M nginx
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
service nginx restart
