#!/usr/bin/env bash
# reload Gunicorn in a graceful way

# Find the process IDs (PIDs) of the Gunicorn workers
pids=$(pgrep gunicorn)

# Send a SIGHUP signal to the master process ID (PID) of Gunicorn
kill -s SIGHUP "$pids"

# Wait for the reload process to complete
sleep 5
