#!/usr/bin/env bash
# Write a Bash script that uses ssh to connect to your server using the
# private key ~/.ssh/school with the user ubuntu

private_key_path="~/.ssh/school"
ssh -i "$private_key_path" ubuntu@100.25.205.228
